### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by krthr** [feathersjs/authentication-client#108] opened 2018-08-30 23:04 UTC
### Steps to reproduce

- [ ] populateAccessToken functions isn't getting the accessToken token property. 

### Expected behavior
Login and create a new resource from the client.

### Actual behavior
Login and getting and error when i try to create a new resource:

```bash
Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at Object.eval (populate-access-token.js?39da:9)
    at promise.then.hookObject (hooks.js?8408:142)
(anonymous) @ populate-access-token.js?39da:9
promise.then.hookObject @ hooks.js?8408:142
...
```

**Module versions** (especially the part that's not working): 
- "@feathersjs/authentication-client": "1.0.3"
- "@feathersjs/feathers": "3.2.0"
- "@feathersjs/socketio-client": "1.1.1"

**NodeJS version**: 8.9.4
**Operating System**: Windows 10

**Comment by krthr** [comment] 2018-08-30 23:05
When i type `ApiClient.get('accessToken')` in the console I get the accessToken

**Comment by daffl** [comment] 2018-08-30 23:34
What logs do you get if you add

```
app.hooks({
  before(context) {
    console.log(context);
    return context;
  }
});
```

In your client side application? Also, does this still happen when explicitly installing `@feathersjs/feathers@3.1.7`?

**Comment by Torge** [comment] 2018-08-31 19:02
I got the same error. I think the problem isn't the access token but hook.params. It is undefined for me.
populateAccessToken tries to Object.assign it.
```
    Object.assign(hook.params, { accessToken: app.get('accessToken') });
```
context in populateAccessToken:
```
"{
  "type": "before",
  "method": "create",
  "path": "draft",
  "data": {}
}"
```
Setting the @feathersjs/feathers version from 3.2.0 to 3.1.7 solved the issue for me.

context in populateAccessToken:
```
{
  "type": "before",
  "method": "create",
  "path": "draft",
  "params": {},
  "data": {}
}
```

**Comment by daffl** [comment] 2018-09-01 00:10
I am not able to reproduce this with a new client build in the [feathers-chat](https://github.com/feathersjs/feathers-chat). How does your client side application setup look like?

**Comment by krthr** [comment] 2018-09-01 00:43
I have a Vue app with `feathers-vuex` plugin

**Comment by krthr** [comment] 2018-09-01 00:50
I have tested it with `@feathersjs/feathers@3.1.7` and it worked....

**Comment by daffl** [comment] 2018-09-02 20:13
Can someone try this with `@feathersjs/feathers@3.2.1` and the latest versions of all other packages. It might've just been a dependency clash that I think should be resolved now.

**Comment by krthr** [comment] 2018-09-03 03:07
It worked fine for me using `@feathersjs/feathers@3.2.1`

**Comment by daffl** [comment] 2018-09-03 15:44
Sweet. I think we can close this then. Anybody running into this issue make sure that all the latest versions are installed.

**Comment by MartinBucko** [comment] 2018-09-07 08:14
Hi guys, i have same issue with latest versions..

```
"dependencies": {
    "@feathersjs/authentication-client": "^1.0.4",
    "@feathersjs/client": "^3.6.0",
    "@feathersjs/socketio-client": "^1.1.2",
    "chart.js": "^2.7.2",
    "chartjs-plugin-datalabels": "^0.4.0",
    "feathers-authentication-management": "^2.0.1",
    "feathers-hooks-common": "^4.16.3",
    "feathers-vuex": "^1.4.8",
    "lodash": "^4.17.10",
    "moment": "^2.22.2",
    "quasar-extras": "^2.0.6",
    "quasar-framework": "^0.17.12",
    "socket.io-client": "^2.1.1",
    "vue": "^2.5.17",
    "vue-chartjs": "^3.4.0",
    "vue-i18n": "^8.1.0",
    "vue-router": "^3.0.1",
    "vuelidate": "^0.7.4",
    "vuelidate-error-extractor": "^2.2.2",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.0.1",
    "@vue/cli-plugin-eslint": "^3.0.1",
    "@vue/cli-service": "^3.0.1",
    "husky": "^0.14.3",
    "lint-staged": "^7.2.2",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.1",
    "vue-cli-plugin-quasar": "^0.2.1",
    "vue-template-compiler": "^2.5.17"
  }
```

**Comment by dottodot** [comment] 2018-09-07 12:07
I think the issue is in @feathersjs/client as the only thing that worked for me was going back to 3.5.6

**Comment by petebytes** [comment] 2018-09-08 07:33
Same exact error for me running latest versions on a project setup on Aug 30th.
Unfortunately setting older versions did not resolve the issue.  

An older nearly identical project is working, however changing all the dependencies from working project to new project did not resolve the issue either.

**Comment by petebytes** [comment] 2018-09-08 08:31
Was able to workaround the issue as follows:
- delete yarn.lock
- delete node_modules
- copy package-lock.json from working project
- npm install

So it seems it was a package that is not explicitly in package.json, as simply copying the working package.json did not work.

**Comment by petebytes** [comment] 2018-09-08 15:54
"@feathersjs/feathers": "3.1.7" works - 3.2.1 does not.
The reason it did not seem to work when I tried 3.1.7 before is that I forgot to remove ^ from package.json and when I installed it was automatically installing 3.2.1

**Comment by daffl** [comment] 2018-09-08 16:13
Since I am not able to reproduce the problem someone has to provide a breaking example. A starting point would be including all the VueJS stuff since that is the main difference I am seeing.

**Comment by petebytes** [comment] 2018-09-08 17:35
@daffl I have a repo here with a works and broken commits.
https://github.com/petebytes/trello-clone.git

**Comment by arjitkhullar** [comment] 2018-09-08 22:35
As @dottodot mentioned, downgrading @feathers/client to v3.5.6 seems to be a workaround for now.

**Comment by joeinnes** [comment] 2018-09-09 14:39
Can confirm, the problem is that hook.params is empty on the create method (but not find). For me it's also in feathers-vuex, same as everyone else in this thread so I think maybe this is a downstream issue.

**Comment by andygott** [comment] 2018-09-14 11:48
I ran into the same thing without using any additional stuff (like Vue). I was using my service like this:

```
feathersClient.service( 'myService' ).create( myData, myParams )
```

But sometimes I call the service with `myParams` undefined, which hadn’t caused a problem using previous feathersjs versions (I don’t think — unless I’d just missed it, which is definitely possible!).

So my fix was simply:

```
feathersClient.service( 'myService' ).create( myData, myParams || {} )
```

Great work on feathersjs — really enjoying using it.

**Comment by daffl** [comment] 2018-09-14 21:26
This issue was moved to feathersjs/feathers#1001

**Closed by daffl** 2018-09-14 21:26 UTC
